# Application Name
spring.application.name=api-gateway

# Server Port
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Disable discovery locator
spring.cloud.gateway.discovery.locator.enabled=false

#ROUTES
# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# AIRLINE SERVICE
spring.cloud.gateway.routes[1].id=airline-service
spring.cloud.gateway.routes[1].uri=lb://airline-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/airlines/**,/api/airports/**

# FLIGHT SERVICE
spring.cloud.gateway.routes[2].id=flight-service
spring.cloud.gateway.routes[2].uri=lb://flight-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/flights/**

# SEAT SERVICE
spring.cloud.gateway.routes[3].id=seat-service
spring.cloud.gateway.routes[3].uri=lb://seat-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/seats/**

# PASSENGER SERVICE
spring.cloud.gateway.routes[4].id=passenger-service
spring.cloud.gateway.routes[4].uri=lb://passenger-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/passengers/**

# BOOKING SERVICE
spring.cloud.gateway.routes[5].id=booking-service
spring.cloud.gateway.routes[5].uri=lb://booking-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/bookings/**

# PAYMENT SERVICE
spring.cloud.gateway.routes[6].id=payment-service
spring.cloud.gateway.routes[6].uri=lb://payment-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/payments/**

# NOTIFICATION SERVICE
spring.cloud.gateway.routes[7].id=notification-service
spring.cloud.gateway.routes[7].uri=lb://notification-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notifications/**

# JWT Secret (must match auth-service)
# jwt.secret=7f9d2c4a8b1e6f3c9a0d5e7b2c4f8a1d9b6c3e5f7a2d8c1b4e6f9a0c3d7b2e5f